spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://db:3306/deposit_service_database?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    initialization-mode: always

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true

server:
  port: 9898
  compression:
    enabled: true